version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: iiot-n8n
    ports:
      - "5678:5678"
    environment:
      # Basic Configuration
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - GENERIC_TIMEZONE=America/Chicago
      
      # Authentication
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=iiot-admin
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD:-StrongPassword123!}
      
      # Webhook Configuration
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_LISTEN_ADDRESS=0.0.0.0
      
      # Database (PostgreSQL for production)
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n-postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD:-n8n_secure_password}
      
      # Security
      - N8N_SECURE_COOKIE=false
      - N8N_HIRING_BANNER_ENABLED=false
      
      # Performance
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168  # 7 days
      
      # Email (optional - for notifications)
      # - N8N_EMAIL_MODE=smtp
      # - N8N_SMTP_HOST=smtp.gmail.com
      # - N8N_SMTP_PORT=587
      # - N8N_SMTP_USER=${SMTP_USER}
      # - N8N_SMTP_PASS=${SMTP_PASS}
      
    volumes:
      # Persistent data
      - n8n_data:/home/node/.n8n
      # Import/export workflows
      - ./n8n-workflows:/opt/workflows:ro
      # Credentials (for Google Sheets, etc.)
      - ../credentials:/opt/credentials:ro
    
    networks:
      - iiot-network
    
    restart: unless-stopped
    
    depends_on:
      - n8n-postgres
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # PostgreSQL database for n8n
  n8n-postgres:
    image: postgres:15-alpine
    container_name: iiot-n8n-db
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-n8n_secure_password}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data
    networks:
      - iiot-network
    restart: unless-stopped
    
    # Health check for PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n -d n8n"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  n8n_data:
    driver: local
  n8n_postgres_data:
    driver: local

networks:
  iiot-network:
    driver: bridge
    # If this network already exists from other services, use:
    # external: true