#!/bin/bash
# Test exact EMQX configuration that should be working

echo "🧪 Testing Exact EMQX Configuration"
echo "==================================="
echo ""

echo "✅ Confirmed working setup:"
echo "- Built-in Database: ENABLED"
echo "- MySQL: DISABLED" 
echo "- User: n8nuser"
echo "- Password: n8npass123"
echo ""

echo "🔍 Check EMQX authentication details:"
docker exec emqxnodec emqx_ctl conf show authentication.1 2>/dev/null | head -15

echo ""
echo "🧪 n8n Test Configurations to Try:"
echo "=================================="
echo ""

echo "Test 1 - Standard username/password:"
echo "  Protocol: mqtt://"
echo "  Host: localhost"
echo "  Port: 1883"
echo "  Username: n8nuser"
echo "  Password: n8npass123"
echo "  Client ID: (leave empty or use: n8n-client)"
echo "  SSL: OFF"
echo ""

echo "Test 2 - If User ID Type is 'clientid':"
echo "  Protocol: mqtt://"
echo "  Host: localhost"
echo "  Port: 1883"
echo "  Username: (leave empty)"
echo "  Password: n8npass123"
echo "  Client ID: n8nuser"
echo "  SSL: OFF"
echo ""

echo "Test 3 - Try both username and client ID:"
echo "  Protocol: mqtt://"
echo "  Host: localhost"
echo "  Port: 1883"
echo "  Username: n8nuser"
echo "  Password: n8npass123"
echo "  Client ID: n8nuser"
echo "  SSL: OFF"
echo ""

echo "🔍 Debug Steps:"
echo "=============="
echo "1. In EMQX Dashboard → Access Control → Authentication"
echo "   - Click on 'Built-in Database' to see details"
echo "   - Check 'User ID Type' setting (username vs clientid)"
echo "   - Check 'Password Hash Algorithm' setting"
echo ""
echo "2. In EMQX Dashboard → Access Control → Users"
echo "   - Verify n8nuser is listed"
echo "   - Check if there are any role/permission settings"
echo ""
echo "3. Check EMQX logs during connection attempt:"
echo "   docker logs emqxnodec --tail 20 -f"
echo "   (then try n8n connection in another window)"
echo ""

echo "💡 Common issues:"
echo "- Password hash mismatch (plain vs hashed)"
echo "- User ID Type mismatch (username vs clientid)"
echo "- Case sensitivity in username/clientid"
echo "- Special characters in password"
echo ""

echo "🎯 Most likely working combination:"
echo "Since you have username 'n8nuser' in the Users section,"
echo "Test 1 should work if the User ID Type is set to 'username'"