#!/bin/bash
# Test with the expected MySQL user from EMQX config

echo "🔍 Testing EMQX with Expected MySQL User"
echo "========================================"
echo ""

echo "📋 EMQX MySQL Configuration Analysis:"
echo "Database: mqttperms"
echo "Expected Username: masterUser (hardcoded in query)"
echo "Password: stored in emqxusers table"
echo ""

echo "💡 The config shows EMQX expects a specific username!"
echo ""
echo "🧪 Let's test n8n with the hardcoded username:"
echo ""
echo "Try these credentials in n8n MQTT:"
echo "=================================="
echo "Protocol: mqtt://"
echo "Host: localhost"
echo "Port: 1883"
echo "Username: masterUser"
echo "Password: emqxPassword"
echo "Client ID: n8n-mqtt-client"
echo "SSL: OFF"
echo ""

echo "🔧 Alternative usernames to try:"
echo "Username: admin"
echo "Password: adminpass123"
echo ""
echo "Username: admin"
echo "Password: public"
echo ""
echo "Username: emqx"
echo "Password: emqx"
echo ""

echo "📊 Evidence that MQTT is working:"
echo "- You saw 3 retained messages today"
echo "- TCP connection to localhost:1883 works"
echo "- EMQX listeners are running"
echo ""
echo "🎯 This suggests authentication issue, not connectivity!"
echo ""
echo "If none of these work, let's enable the built-in database auth instead."