name: Claude Code Action
on:
  issue_comment:
    types: [created, edited]
  pull_request_review:
    types: [submitted]
  issues:
    types: [opened]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  claude:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - uses: slimstrongarm/claude-code-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Option 1: Use Claude Max session key (preferred)
          session-key: ${{ secrets.CLAUDE_MAX_SESSION_KEY }}
          # Option 2: Use Anthropic API key (fallback)
          # anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # Additional configuration
          max-tokens: 4000
          temperature: 0.3
          
          # Industrial IoT Stack specific context
          system-prompt: |
            You are Claude assisting with an Industrial IoT Stack project.
            Key components: EMQX MQTT, n8n workflows, Discord integration, 
            Google Sheets API, Node-RED, Ignition Edge.
            Provide specific, actionable advice for industrial automation.
