name: Claude Code Action
on:
  issue_comment:
    types: [created, edited]
  pull_request_review:
    types: [submitted]
  issues:
    types: [opened]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  claude:
    if: contains(github.event.comment.body, '@claude') || contains(github.event.issue.body, '@claude') || contains(github.event.review.body, '@claude')
    runs-on: ubuntu-latest
    steps:
      - uses: slimstrongarm/claude-code-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          # OR for Claude Max OAuth (uncomment and comment above line):
          # session-key: ${{ secrets.CLAUDE_MAX_SESSION_KEY }}